# run on container environment
sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.npm
    - vendor
    - $HOME/.composer/cache
    - tests/cache

language: php

notifications:
  email:
    on_success: change
    on_failure: always

php:
  - 7.3
  - 5.6

env:
  matrix:
    # WP latest stable:
    - WP_VERSION=*
    # WP nightly:
    - WP_VERSION=dev-nightly

matrix:
  fast_finish: true

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

install:
  - travis_retry composer install --no-suggest
  - travis_retry composer require --dev --update-with-dependencies --no-suggest --prefer-dist roots/wordpress="${WP_VERSION}"

script:
  - |
    if [ "$TRAVIS_PHP_VERSION" == "7.3" ] && [ "$WP_VERSION" == "*" ]; then
      composer test:cs
    fi
  - composer test:ut
