# run on container environment
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

language: php

notifications:
  email:
    on_success: change
    on_failure: always

php:
  - 7.2
  - 5.6

env:
  global:
    # WPORG_PASSWORD
    - secure: "EqtfI7W2K0H1Zpx8Kb0qTQAz6HNnJj6fupjXJkWhlzt4z79VM8TRuSn3fzbSwJtkHWNwp2jfR/wTu4SVCmlNwMUWSV5fpMGDXBxksWm6SqGjWw8rF2L746btfgoqnAVie1Vw2q6Y7A1opNnwTA29cgEZmoZjHV1DvED4BtXyxdE="
  matrix:
    # WP latest stable:
    - WP_VERSION=latest
    # WP nightly:
    - WP_VERSION=nightly

jobs:
  include:
    - stage: deploy
      before_script:
        - npm install -g grunt-cli
        - npm install
        - gem install sass
        - grunt --version
        - git status
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: grunt deploy:ci
          on:
            tags: true

matrix:
  fast_finish: true

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

install:
  - composer install

before_script:
  - php --version
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - composer test
