# run on container environment
sudo: false

cache:
  directories:
    - $HOME/.npm
    - vendor
    - $HOME/.composer/cache

language: php

notifications:
  email:
    on_success: change
    on_failure: always

php:
  - 7.2
  - 5.6

env:
  global:
    # WPORG_PASSWORD
    - secure: "EqtfI7W2K0H1Zpx8Kb0qTQAz6HNnJj6fupjXJkWhlzt4z79VM8TRuSn3fzbSwJtkHWNwp2jfR/wTu4SVCmlNwMUWSV5fpMGDXBxksWm6SqGjWw8rF2L746btfgoqnAVie1Vw2q6Y7A1opNnwTA29cgEZmoZjHV1DvED4BtXyxdE="
  matrix:
    # WP latest stable:
    - WP_VERSION=*
    # WP nightly:
    - WP_VERSION=dev-nightly

stages:
  - sniff
  - test
  - deploy

jobs:
  include:
    - stage: sniff
      script:
        - composer test:cs
    - stage: deploy
      before_script:
        - npm install -g grunt-cli
        - npm install
        - gem install sass
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: grunt deploy:ci
          on:
            tags: true

matrix:
  fast_finish: true

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

install:
  - travis_retry composer install --no-suggest
  - travis_retry composer require --dev --update-with-dependencies --no-suggest --prefer-dist roots/wordpress="${WP_VERSION}"

script:
  - composer test:ut
