name: Deploy Tag
on:
  release:
    types: [published]

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-18.04
    steps:
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://wordpress.org/plugins/query-monitor
        environment: WordPress.org
        description: "Deploy version ${{ github.event.release.tag_name }} to the plugin directory"

    - name: Checkout repository
      uses: actions/checkout@v1

      # @TODO need to cache the npm dependencies
    - name: Install Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build

    - name: Populate Changelog
      run: node .github/workflows/changelog.js readme.txt
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@1.4.1
      env:
        SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}

    - name: Deployment Succeeded
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: success
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Deployment Failed
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: failure
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  github:
    name: GitHub Milestones
    runs-on: ubuntu-18.04
    steps:
    - name: Get next versions
      id: semvers
      uses: WyriHaximus/github-action-next-semvers@v1.0
      with:
        version: ${{ github.event.release.tag_name }}

    - name: Create next patch milestone
      uses: WyriHaximus/github-action-create-milestone@0.1.0
      with:
        title: ${{ steps.semvers.outputs.patch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create next minor milestone
      uses: WyriHaximus/github-action-create-milestone@0.1.0
      with:
        title: ${{ steps.semvers.outputs.minor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create next major milestone
      uses: WyriHaximus/github-action-create-milestone@0.1.0
      with:
        title: ${{ steps.semvers.outputs.major }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
